modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
updateJSONURL="https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/indicatia_version.json"
issueTrackerURL="https://github.com/SteveKunG/Indicatia/issues"

[[mods]]
modId="indicatia"
version="4.0.0"
displayName="Indicatia"
description="Simple in-game info and small utilities!"
displayURL="https://www.curseforge.com/minecraft/mc-mods/indicatia"
logoFile="logo.png"
authors="SteveKunG"

[[dependencies.indicatia]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.indicatia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="CLIENT"

[[dependencies.indicatia]]
    modId="stevekungs_lib"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="CLIENT"