modLoader="javafml"
loaderVersion="[28,)"
updateJSONURL="https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/indicatia_version.json"
issueTrackerURL="https://github.com/SteveKunG/Indicatia/issues"

[[mods]]
modId="indicatia"
version="2.0.3"
displayName="Indicatia"
description="Simple in-game info and utilities!"
displayURL="https://minecraft.curseforge.com/projects/indicatia"
logoFile="logo.png"
authors="SteveKunG"

[[dependencies.indicatia]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.indicatia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="CLIENT"

[[dependencies.indicatia]]
    modId="stevekungs_lib"
    mandatory=true
    versionRange="[2.0.4,)"
    ordering="NONE"
    side="CLIENT"